# Generated by Django 5.1.5 on 2025-01-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='owner',
            new_name='user',
        ),
    ]
